import { formatNumber } from './format.ts';
import type { GitHubStats, ProfileConfig } from './types.ts';

export const START_MARKER = '<!-- GITHUB_STATS_START -->';
export const END_MARKER = '<!-- GITHUB_STATS_END -->';

export interface CardImages {
  wideDark: string;
  wideLight: string;
  narrowDark: string;
  narrowLight: string;
}

/** Below this viewport width GitHub is shown the stacked, phone-sized card. */
const NARROW_BREAKPOINT = '600px';

/** "1 star", "206 stars" */
const countOf = (value: number, noun: string, suffix = ''): string =>
  `${formatNumber(value)} ${noun}${value === 1 ? '' : 's'}${suffix}`;

/** Plain-text summary of the card, used as the image alt text and SVG title. */
export function describeCard(profile: ProfileConfig, stats: GitHubStats): string {
  const facts = [
    countOf(stats.publicRepos, 'public repo'),
    countOf(stats.stars, 'star'),
    countOf(stats.forks, 'fork'),
    countOf(stats.commits, 'commit'),
    countOf(stats.pullRequests, 'pull request'),
    countOf(stats.issues, 'issue'),
    countOf(stats.followers, 'follower'),
    countOf(stats.contributionsLastYear, 'contribution', ' in the past year'),
    `${formatNumber(stats.linesAdded - stats.linesDeleted)} net lines of code`,
  ];
  return `${profile.name} (@${profile.login}): ASCII portrait with system-info style profile. GitHub stats: ${facts.join(', ')}.`;
}

export function renderStatsBlock(images: CardImages, description: string): string {
  const alt = description.replace(/&/g, '&amp;').replace(/"/g, '&quot;');
  return [
    '<!-- Generated by scripts/update-github-stats.ts. Edits between these markers are overwritten. -->',
    '<picture>',
    `  <source media="(max-width: ${NARROW_BREAKPOINT}) and (prefers-color-scheme: dark)" srcset="${images.narrowDark}">`,
    `  <source media="(max-width: ${NARROW_BREAKPOINT})" srcset="${images.narrowLight}">`,
    `  <source media="(prefers-color-scheme: dark)" srcset="${images.wideDark}">`,
    `  <img src="${images.wideLight}" alt="${alt}" width="100%">`,
    '</picture>',
  ].join('\n');
}

function indexOfOnly(text: string, marker: string): number {
  const first = text.indexOf(marker);
  if (first === -1) throw new Error(`README is missing the ${marker} marker`);
  if (text.indexOf(marker, first + marker.length) !== -1) throw new Error(`README contains ${marker} more than once`);
  return first;
}

/**
 * Replaces whatever sits between the markers with `block`, leaving every byte
 * outside them untouched. Refuses to guess if the markers are missing or out of order.
 */
export function replaceStatsBlock(readme: string, block: string): string {
  const start = indexOfOnly(readme, START_MARKER);
  const end = indexOfOnly(readme, END_MARKER);
  if (end < start) throw new Error(`${END_MARKER} appears before ${START_MARKER} in README`);

  const eol = readme.includes('\r\n') ? '\r\n' : '\n';
  const body = block.split('\n').join(eol);
  return readme.slice(0, start + START_MARKER.length) + eol + body + eol + readme.slice(end);
}
